SchoolJournal.App/SchoolJournal/Controllers/GradeController.cs
using SchoolJournal.BusinessLogic;
using SchoolJournal.Interfaces;
using SchoolJournal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolJournal.Controllers
{
    //[MyExceptionHandler]
    public class GradeController : Controller
    {
        private readonly IGradeManager manager;
        private readonly IPopulateList populate;

        public GradeController()
        {
            manager = new GradeManager();
            populate = new PopulateList();
        }

        //[MyExceptionHandler]
        public ActionResult Index(int? id)
        {
            if (id != null)
                return View(manager.GetGradesByStudentID(id).ToList());
            return View(manager.GetAllGrades().ToList());
        }

        //[MyExceptionHandler]
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
                return HttpNotFound();

            Grade grade = manager.GetGradeByID(id);
            grade.StudentsList = populate.StudentsList();
            grade.SemestersList = populate.SemestersList();
            grade.CoursesList = populate.CoursesList();

            if (grade == null)
                return HttpNotFound();

            return View(grade);
        }

        //[MyExceptionHandler]
        [HttpGet]
        public ActionResult Create()
        {
            Grade grade = new Grade();
            grade.StudentsList = populate.StudentsList();
            grade.SemestersList = populate.SemestersList();
            grade.CoursesList = populate.CoursesList();

            if (grade == null)
                return HttpNotFound();

            return View(grade);
        }

        //[MyExceptionHandler]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Grade grade)
        {
            if (ModelState.IsValid)
            {
                manager.AddGrade(grade);
                return RedirectToAction("Index");
            }
            return View(grade);
        }

        //[MyExceptionHandler]
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return HttpNotFound();

            Grade grade = manager.GetGradeByID(id);
            grade.StudentsList = populate.StudentsList();
            grade.SemestersList = populate.SemestersList();
            grade.CoursesList = populate.CoursesList();

            if (grade == null)
                return HttpNotFound();

            return View(grade);
        }

        //[MyExceptionHandler]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GradeID,StudentID,SemesterID,CourseID,Mark,DateOfMark,GradingWeight,Observations")]Grade grade, int? id)
        {
            if (id == null)
                return HttpNotFound();

            if (ModelState.IsValid)
            {
                manager.UpdateGrade(grade);
                return RedirectToAction("Index");
            }

            return View(grade);
        }

        //[MyExceptionHandler]
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return HttpNotFound();

            Grade grade = manager.GetGradeByID(id);

            if (grade == null)
                return HttpNotFound();

            return View(grade);
        }

        //[MyExceptionHandler]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            manager.DeleteGrade(id);
            return RedirectToAction("Index");
        }
    }
}

SchoolJournal.App/SchoolJournal/Views/Grade/Create.cshtml
@model SchoolJournal.Models.Grade

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Grade</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StudentID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.StudentID, Model.StudentsList, "Please select")
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SemesterID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SemesterID, Model.SemestersList, "Please select")
                @Html.ValidationMessageFor(model => model.SemesterID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CourseID, Model.CoursesList, "Please select")
                @Html.ValidationMessageFor(model => model.CourseID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mark, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfMark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfMark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfMark, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GradingWeight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GradingWeight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GradingWeight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observations, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observations, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observations, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SchoolJournal.App/SchoolJournal/Views/Grade/CreateUD.cshtml
@model SchoolJournal.Models.Grade

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/_Layout.cshtml";
}

<h2>ADD GRADE</h2>

@using (Html.BeginForm("Create", "Grade", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Grade details</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(t => t.Students.StudentName, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.DropDownListFor(t => t.StudentID, Model.StudentsList, "Please select")
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.Semesters.SemesterNumber, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.DropDownListFor(t => t.SemesterID, Model.SemestersList, "Please select")
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.Courses.CourseName, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.DropDownListFor(t => t.CourseID, Model.CoursesList, "Please select")
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.Mark, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.EditorFor(t => t.Mark, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(t => t.Mark, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.DateOfMark, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.EditorFor(t => t.DateOfMark, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(t => t.DateOfMark, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.GradingWeight, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.TextBoxFor(t => t.GradingWeight, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(t => t.GradingWeight, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.Observations, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.TextBoxFor(t => t.Observations, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(t => t.Observations, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-3 col-md-9">
            <input type="submit" value="Add" class="btn btn-primary" />
        </div>
    </div>
</div>
}
<div>
    @Html.ActionLink("Back to list", "Index", "Grade")
</div>

SchoolJournal.App/SchoolJournal/Views/Grade/Delete.cshtml
@model SchoolJournal.Models.Grade
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/_Layout.cshtml";
}

<h2>DELETE</h2>
<h3>Are you sure you want to delete this information?</h3>

<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(t => t.GradeID)</dt>
        <dd>@Html.DisplayFor(t => t.GradeID)</dd>

        <dt>@Html.DisplayNameFor(t => t.Students.StudentName)</dt>
        <dd>@Html.DisplayFor(t => t.Students.StudentName)</dd>

        <dt>@Html.DisplayNameFor(t => t.Semesters.SemesterNumber)</dt>
        <dd>@Html.DisplayFor(t => t.Semesters.SemesterNumber)/@Html.DisplayFor(t => t.Semesters.SchoolYear)</dd>

        <dt>@Html.DisplayNameFor(t => t.Courses.CourseName)</dt>
        <dd>@Html.DisplayFor(t => t.Courses.CourseName)/(lvl.@Html.DisplayFor(t => t.Courses.LevelYear))</dd>

        <dt>@Html.DisplayNameFor(t => t.Mark)</dt>
        <dd>@Html.DisplayFor(t => t.Mark)</dd>

        <dt>@Html.DisplayNameFor(t => t.DateOfMark)</dt>
        <dd>@Html.DisplayFor(t => t.DateOfMark)</dd>

        <dt>@Html.DisplayNameFor(t => t.GradingWeight)</dt>
        <dd>@Html.DisplayFor(t => t.GradingWeight)</dd>

        <dt>@Html.DisplayNameFor(t => t.Observations)</dt>
        <dd>@Html.DisplayFor(t => t.Observations)</dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <input type="submit" value="Delete" class="btn btn-primary" />
            @Html.ActionLink("Cancel", "Index", "Grade")
        </div>
    }
</div>

SchoolJournal.App/SchoolJournal/Views/Grade/Details.cshtml
@model SchoolJournal.Models.Grade
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/_Layout.cshtml";
}

<div>
    <h2>DETAILS</h2>
    <br />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Students.StudentName)</dt>
        <dd>@Html.DisplayFor(model => model.Students.StudentName)</dd>

        <dt>@Html.DisplayNameFor(model => model.Semesters.SemesterNumber)</dt>
        <dd>@Html.DisplayFor(model => model.Semesters.SemesterNumber)/@Html.DisplayFor(model => model.Semesters.SchoolYear)</dd>

        <dt>@Html.DisplayNameFor(model => model.Courses.CourseName)</dt>
        <dd>@Html.DisplayFor(model => model.Courses.CourseName)/(lvl.@Html.DisplayFor(model => model.Courses.LevelYear))</dd>

        <dt>@Html.DisplayNameFor(model => model.Mark)</dt>
        <dd>@Html.DisplayFor(model => model.Mark)</dd>

        <dt>@Html.DisplayNameFor(model => model.DateOfMark)</dt>
        <dd>@Html.DisplayFor(model => model.DateOfMark)</dd>

        <dt>@Html.DisplayNameFor(model => model.GradingWeight)</dt>
        <dd>@Html.DisplayFor(model => model.GradingWeight)</dd>

        <dt>@Html.DisplayNameFor(model => model.Observations)</dt>
        <dd>@Html.DisplayFor(model => model.Observations)</dd>
    </dl>

    <p>@Html.ActionLink("Back to grades", "Index", "Grade") | @Html.ActionLink("Edit", "Edit", "Grade", new { @id = Model.GradeID }, null)</p>
</div>

SchoolJournal.App/SchoolJournal/Views/Grade/Edit.cshtml
@model SchoolJournal.Models.Grade
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/_Layout.cshtml";
}

<h2>UPDATE</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(g => g.GradeID)

<dl class="dl-horizontal">
    <dt>@Html.LabelFor(g => g.Students.StudentName, new { @class = "control-label col-md-3" })</dt>
    <dd>
        @Html.DropDownListFor(g => g.StudentID, Model.StudentsList, "Please select")
        @Html.ValidationMessageFor(g => g.StudentID)
    </dd>

    <dt>@Html.LabelFor(g => g.Semesters.SemesterNumber, new { @class = "control-label col-md-3" })</dt>
    <dd>
        @Html.DropDownListFor(g => g.SemesterID, Model.SemestersList, "Please select")
        @Html.ValidationMessageFor(g => g.SemesterID)
    </dd>

    <dt>@Html.LabelFor(g => g.Courses.CourseName, new { @class = "control-label col-md-3" })</dt>
    <dd>
        @Html.DropDownListFor(g => g.CourseID, Model.CoursesList, "Please select")
        @Html.ValidationMessageFor(g => g.CourseID)
    </dd>

    <dt>@Html.DisplayNameFor(c => c.Mark)</dt>
    <dd>
        @Html.TextBoxFor(c => c.Mark, null, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.Mark)
    </dd>

    <dt>@Html.DisplayNameFor(c => c.DateOfMark)</dt>
    <dd>
        @Html.TextBoxFor(c => c.DateOfMark, null, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.DateOfMark)
    </dd>

    <dt>@Html.DisplayNameFor(c => c.GradingWeight)</dt>
    <dd>
        @Html.TextAreaFor(c => c.GradingWeight, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.GradingWeight)
    </dd>

    <dt>@Html.DisplayNameFor(c => c.Observations)</dt>
    <dd>
        @Html.TextAreaFor(c => c.Observations, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.Observations)
    </dd>

</dl>

    <input type="submit" value="Save" class="btn btn-primary" />
    @Html.ActionLink("Cancel", "Index", "Grade");
}

SchoolJournal.App/SchoolJournal/Views/Grade/Index.cshtml
@model IEnumerable<SchoolJournal.Models.Grade>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_Layout.cshtml";
}

<h2>Grades</h2>
<p>
    <strong>@Html.ActionLink("ADD NEW", "Create", "Grade")</strong>
</p>
<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Students.StudentName)</th>
            <th>@Html.DisplayNameFor(model => model.Semesters.SemesterNumber)</th>
            <th>@Html.DisplayNameFor(model => model.Courses.CourseName)</th>
            <th>@Html.DisplayNameFor(model => model.Mark)</th>
            <th>@Html.DisplayNameFor(model => model.DateOfMark)</th>
            <th>@Html.DisplayNameFor(model => model.GradingWeight)</th>
            <th>@Html.DisplayNameFor(model => model.Observations)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var grade in Model)
        {
            <tr>
                <td>@Html.DisplayFor(model => grade.Students.StudentName)</td>
                <td>@Html.DisplayFor(model => grade.Semesters.SemesterNumber)/@Html.DisplayFor(model => grade.Semesters.SchoolYear)</td>
                <td>@Html.DisplayFor(model => grade.Courses.CourseName)</td>
                <td>@Html.DisplayFor(model => grade.Mark)</td>
                <td>@Html.DisplayFor(model => grade.DateOfMark)</td>
                <td>@Html.DisplayFor(model => grade.GradingWeight)</td>
                <td>@Html.DisplayFor(model => grade.Observations)</td>
                <td>
                    @Html.ActionLink("Details", "Details", "Grade", new { @id = grade.GradeID }, null) |
                    @Html.ActionLink("Edit", "Edit", "Grade", new { @id = grade.GradeID }, null) |
                    @Html.ActionLink("Delete", "Delete", "Grade", new { @id = grade.GradeID }, null)
                </td>
            </tr>
        }
    </tbody>
</table>