SchoolJournal.App/SchoolJournal/Controllers/HomeworkController.cs
using SchoolJournal.BusinessLogic;
using SchoolJournal.Interfaces;
using SchoolJournal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolJournal.Controllers
{
    //[MyExceptionHandler]
    public class HomeworkController : Controller
    {
        private readonly IHomeworkManager manager;
        private readonly IPopulateList populate;

        public HomeworkController()
        {
            manager = new HomeworkManager();
            populate = new PopulateList();
        }

        //[MyExceptionHandler]
        public ActionResult Index(int? id)
        {
            if (id != null)
                return View(manager.GetHomeworkByStudentID(id).ToList());
            return View(manager.GetAllHomeworks().ToList());
        }

        //[MyExceptionHandler]
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
                return HttpNotFound();

            Homework homework = manager.GetHomeworkByID(id);
            homework.StudentsList = populate.StudentsList();
            homework.CoursesList = populate.CoursesList();

            if (homework == null)
                return HttpNotFound();

            return View(homework);
        }

        //[MyExceptionHandler]
        [HttpGet]
        public ActionResult Create()
        {
            Homework homework = new Homework();
            homework.StudentsList = populate.StudentsList();
            homework.CoursesList = populate.CoursesList();

            return View(homework);
        }

        //[MyExceptionHandler]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudentID,CourseID,DateOfHomework,DueDate,Details,HomeworkStatus")] Homework homework)
        {
            if (ModelState.IsValid)
            {
                manager.AddHomework(homework);
                return RedirectToAction("Index");
            }
            return View(homework);
        }

        //[MyExceptionHandler]
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return HttpNotFound();

            Homework homework = manager.GetHomeworkByID(id);
            homework.StudentsList = populate.StudentsList();
            homework.CoursesList = populate.CoursesList();

            if (homework == null)
                return HttpNotFound();

            return View(homework);
        }

        //[MyExceptionHandler]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "HomeworkID,StudentID,CourseID,DateOfHomework,DueDate,Details,HomeworkStatus")]Homework homework, int? id)
        {
            if (id == null)
                return HttpNotFound();

            if (ModelState.IsValid)
            {
                manager.UpdateHomework(homework);
                return RedirectToAction("Index");
            }

            return View(homework);
        }

        //[MyExceptionHandler]
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return HttpNotFound();

            Homework homework = manager.GetHomeworkByID(id);

            if (homework == null)
                return HttpNotFound();

            return View(homework);
        }

        //[MyExceptionHandler]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            manager.DeleteHomework(id);
            return RedirectToAction("Index");
        }
    }
}

SchoolJournal.App/SchoolJournal/Views/Homework/Create.cshtml
@model SchoolJournal.Models.Homework
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/_Layout.cshtml";
}

<h2>ADD HOMEWORK</h2>

@using (Html.BeginForm("Create", "Homework", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Homework details</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(t => t.Students.StudentName, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.DropDownListFor(t => t.StudentID, Model.StudentsList, "Please select")
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.Courses.CourseName, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.DropDownListFor(t => t.CourseID, Model.CoursesList, "Please select")
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.DateOfHomework, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.EditorFor(t => t.DateOfHomework, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(t => t.DateOfHomework, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.DueDate, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.EditorFor(t => t.DueDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(t => t.DueDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(t => t.Details, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.TextAreaFor(t => t.Details, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(t => t.Details, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(h => h.HomeworkStatus, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.DropDownList("HomeworkStatus", new List<SelectListItem> { new SelectListItem { Text="TO DO", Value="TO DO"},
                                                                    new SelectListItem { Text="IN PROGRESS", Value="IN PROGRESS"},
                                                                    new SelectListItem { Text="FINISHED", Value="FINISHED"} },"Select status")
            @Html.ValidationMessageFor(h => h.HomeworkStatus, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-3 col-md-9">
            <input type="submit" value="Add" class="btn btn-primary" />
        </div>
    </div>
</div>
}
<div>
    @Html.ActionLink("Back to list", "Index", "Homework")
</div>

SchoolJournal.App/SchoolJournal/Views/Homework/Delete.cshtml
@model SchoolJournal.Models.Homework
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/_Layout.cshtml";
}

<h2>DELETE</h2>
<h3>Are you sure you want to delete this information?</h3>

<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(t => t.HomeworkID)</dt>
        <dd>@Html.DisplayFor(t => t.HomeworkID)</dd>

        <dt>@Html.DisplayNameFor(t => t.Students.StudentName)</dt>
        <dd>@Html.DisplayFor(t => t.Students.StudentName)</dd>

        <dt>@Html.DisplayNameFor(t => t.Courses.CourseName)</dt>
        <dd>@Html.DisplayFor(t => t.Courses.CourseName)</dd>

        <dt>@Html.DisplayNameFor(t => t.DateOfHomework)</dt>
        <dd>@Html.DisplayFor(t => t.DateOfHomework)</dd>

        <dt>@Html.DisplayNameFor(t => t.DueDate)</dt>
        <dd>@Html.DisplayFor(t => t.DueDate)</dd>

        <dt>@Html.DisplayNameFor(t => t.Details)</dt>
        <dd>@Html.DisplayFor(t => t.Details)</dd>

        <dt>@Html.DisplayNameFor(t => t.HomeworkStatus)</dt>
        <dd>@Html.DisplayFor(t => t.HomeworkStatus)</dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <input type="submit" value="Delete" class="btn btn-primary" />
            @Html.ActionLink("Cancel", "Index", "Homework")
        </div>
    }
</div>

SchoolJournal.App/SchoolJournal/Views/Homework/Details.cshtml
@model SchoolJournal.Models.Homework
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/_Layout.cshtml";
}

<div>
    <h2>DETAILS</h2>
    <br />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Students.StudentName)</dt>
        <dd>@Html.DisplayFor(model => model.Students.StudentName)</dd>

        <dt>@Html.DisplayNameFor(model => model.Courses.CourseName)</dt>
        <dd>@Html.DisplayFor(model => model.Courses.CourseName)</dd>

        <dt>@Html.DisplayNameFor(model => model.DateOfHomework)</dt>
        <dd>@Html.DisplayFor(model => model.DateOfHomework)</dd>

        <dt>@Html.DisplayNameFor(model => model.DueDate)</dt>
        <dd>@Html.DisplayFor(model => model.DueDate)</dd>

        <dt>@Html.DisplayNameFor(model => model.Details)</dt>
        <dd>@Html.DisplayFor(model => model.Details)</dd>

        <dt>@Html.DisplayNameFor(model => model.HomeworkStatus)</dt>
        <dd>@Html.DisplayFor(model => model.HomeworkStatus)</dd>
    </dl>

    <p>@Html.ActionLink("Back to courses", "Index", "Homework") | @Html.ActionLink("Edit", "Edit", "Homework", new { @id = Model.HomeworkID }, null)</p>
</div>

SchoolJournal.App/SchoolJournal/Views/Homework/Edit.cshtml
@model SchoolJournal.Models.Homework
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/_Layout.cshtml";
}

<h2>UPDATE</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(c => c.HomeworkID)

<dl class="dl-horizontal">
    <dt>@Html.LabelFor(t => t.Students.StudentName, new { @class = "control-label col-md-3" })</dt>
    <dd>
        @Html.DropDownListFor(t => t.StudentID, Model.StudentsList, "Please select")
        @Html.ValidationMessageFor(c => c.StudentID)
    </dd>

    <dt>@Html.LabelFor(t => t.Courses.CourseName, new { @class = "control-label col-md-3" })</dt>
    <dd>
        @Html.DropDownListFor(t => t.CourseID, Model.CoursesList, "Please select")
        @Html.ValidationMessageFor(c => c.CourseID)
    </dd>

    <dt>@Html.DisplayNameFor(c => c.DateOfHomework)</dt>
    <dd>
        @Html.TextBoxFor(c => c.DateOfHomework, null, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.DateOfHomework)
    </dd>

    <dt>@Html.DisplayNameFor(c => c.DueDate)</dt>
    <dd>
        @Html.TextBoxFor(c => c.DueDate, null, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.DueDate)
    </dd>

    <dt>@Html.DisplayNameFor(c => c.Details)</dt>
    <dd>
        @Html.TextAreaFor(c => c.Details, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.Details)
    </dd>

    <dt>@Html.LabelFor(h => h.HomeworkStatus, new { @class = "control-label col-md-3" })</dt>
    <dd>
        @Html.DropDownList("HomeworkStatus", new List<SelectListItem> { new SelectListItem { Text="TO DO", Value="TO DO"},
                                                                new SelectListItem { Text="IN PROGRESS", Value="IN PROGRESS"},
                                                                new SelectListItem { Text="FINISHED", Value="FINISHED"} },"Select status")
        @Html.ValidationMessageFor(h => h.HomeworkStatus, "", new { @class = "text-danger" })
    </dd>

</dl>

    <input type="submit" value="Save" class="btn btn-primary" />
    @Html.ActionLink("Cancel", "Index", "Homework");
}

SchoolJournal.App/SchoolJournal/Views/Homework/Index.cshtml
@model IEnumerable<SchoolJournal.Models.Homework>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_Layout.cshtml";
}

<h2>Homeworks</h2>
<p>
    <strong>@Html.ActionLink("ADD NEW", "Create", "Homework")</strong>
</p>
<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Students.StudentName)</th>
            <th>@Html.DisplayNameFor(model => model.Courses.CourseName)</th>
            <th>@Html.DisplayNameFor(model => model.DateOfHomework)</th>
            <th>@Html.DisplayNameFor(model => model.DueDate)</th>
            <th>@Html.DisplayNameFor(model=>model.Details)</th>
            <th>@Html.DisplayNameFor(model=>model.HomeworkStatus)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var homework in Model)
        {
            <tr>
                <td>@Html.DisplayFor(model => homework.Students.StudentName)</td>
                <td>@Html.DisplayFor(model => homework.Courses.CourseName)</td>
                <td>@Html.DisplayFor(model => homework.DateOfHomework)</td>
                <td>@Html.DisplayFor(model => homework.DueDate)</td>
                <td>@Html.DisplayFor(model => homework.Details)</td>
                <td>@Html.DisplayFor(model => homework.HomeworkStatus)</td>
                <td>
                    @Html.ActionLink("Details", "Details", "Homework", new { @id = homework.HomeworkID }, null) |
                    @Html.ActionLink("Edit", "Edit", "Homework", new { @id = homework.HomeworkID }, null) |
                    @Html.ActionLink("Delete", "Delete", "Homework", new { @id = homework.HomeworkID }, null)
                </td>
            </tr>
        }
    </tbody>
</table>