SchoolJournal/SchoolJournalApp/Controllers/SemestersController.cs
using PagedList;
using SchoolJournalBusinessLogic;
using SchoolJournalInterfaces;
using SchoolJournalModels;
using System.Web.Mvc;

namespace SchoolJournalApp.Controllers
{
    public class SemestersController : Controller
    {
        private ISemestersManager manager;

        public SemestersController()
        {
            manager = new SemestersManager();
        }

        public ActionResult Index(string option, string search, int? pageNumber)
        {
            if (option == "Number")
            {
                return View(manager.GetByNumber(search).ToPagedList(pageNumber ?? 1, 5));
            }
            else if (option == "Year")
            {
                return View(manager.GetByYear(search).ToPagedList(pageNumber ?? 1, 5));
            }
            else
            {
                return View(manager.GetAllSemesters().ToPagedList(pageNumber ?? 1, 5));
            }
        }

        public ActionResult Details(int id)
        {
            var semester = manager.Get(id);
            return View(semester);
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            var semester = manager.Get(id);
            if (semester == null)
            {
                return HttpNotFound();
            }
            return View(semester);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update([Bind(Include = "SemesterID,SemesterNumber,SchoolYear")]Semesters semester)
        {
            if (ModelState.IsValid)
            {
                manager.Save(semester);
                return RedirectToAction("Index");
            }
            return View(semester);
        }

        [HttpGet]
        public ActionResult Delete(int id, bool? saveChangesError = false)
        {
            if (saveChangesError.GetValueOrDefault())
                ViewBag.ErrorMessage = "Delete failed! Try again or see your sysadmin!";
            Semesters semester = manager.Get(id);
            if (semester == null)
            {
                return HttpNotFound();
            }
            return View(semester);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            if (ModelState.IsValid)
            {
                manager.Delete(id);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Delete", new { id, saveChangesError = true });
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add([Bind(Include = "SemesterID,SemesterNumber,SchoolYear")]Semesters semester)
        {
            if (ModelState.IsValid)
            {
                manager.Add(semester);
                return RedirectToAction("Index");
            }
            return View(semester);
        }
    }
}

SchoolJournal/SchoolJournalApp/Controllers/SubjectController.cs
using PagedList;
using SchoolJournalBusinessLogic;
using SchoolJournalInterfaces;
using SchoolJournalModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolJournalApp.Controllers
{
    public class SubjectController : Controller
    {
        private ISubjectManager manager;

        public SubjectController()
        {
            manager = new SubjectManager();
        }

        public ActionResult Index(string option, string search, int? pageNumber)
        {
            if (option == "Subject")
                return View(manager.GetBySubject(search).ToPagedList(pageNumber ?? 1, 5));
            else if (option == "Teacher")
                return View(manager.GetByTeacher(search).ToPagedList(pageNumber ?? 1, 5));
            else if (option == "Level")
                return View(manager.GetByYear(search).ToPagedList(pageNumber ?? 1, 5));
            else
                return View(manager.GetAll().ToPagedList(pageNumber ?? 1, 5));
        }

        public ActionResult Details(int id)
        {
            return View(manager.Get(id));
        }

        [HttpGet]
        public ActionResult Delete(int id, bool? saveChangesError = false)
        {
            if (saveChangesError.GetValueOrDefault())
                ViewBag.ErrorMessage = "Delete failed! Try again or see your sysadmin!";
            Subject subject = manager.Get(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            if (ModelState.IsValid)
            {
                manager.Delete(id);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Delete", new { id, saveChangesError = true });
        }

        [HttpGet]
        public ActionResult Update(int id)
        {
            var subject = manager.Get(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update([Bind(Include = "SubjectID,SubjectName,LevelYear,TeacherID")]Subject subject)
        {
            if (ModelState.IsValid)
            {
                manager.Save(subject);
                return RedirectToAction("Index");
            }
            return View(subject);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View(manager.SubjectWithTeachersList());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add([Bind(Include = "SubjectID,SubjectName,LevelYear,TeacherID")]Subject subject)
        {
            if (ModelState.IsValid)
            {
                manager.Add(subject);
                return RedirectToAction("Index");
            }
            return View(subject);
        }
    }
}

SchoolJournal/SchoolJournalApp/Views/Semesters/Add.cshtml
@model SchoolJournalModels.Semesters

<h2>ADD SEMESTER</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Semester details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(s => s.SemesterNumber, new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(s => s.SemesterNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(s => s.SemesterNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(s => s.SchoolYear, new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(s => s.SchoolYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(s => s.SchoolYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-9">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to list", "Index", "Semesters")
</div>

SchoolJournal/SchoolJournalApp/Views/Semesters/Delete.cshtml
@model SchoolJournalModels.Semesters


<h2>DELETE</h2>
<h3>Are you sure you want to delete this information?</h3>

<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(s => s.SemesterID)
        </dt>
        <dd>
            @Html.DisplayFor(s => s.SemesterID)
        </dd>

        <dt>
            @Html.DisplayNameFor(s => s.SemesterNumber)
        </dt>
        <dd>
            @Html.DisplayFor(s => s.SemesterNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(s => s.SchoolYear)
        </dt>
        <dd>
            @Html.DisplayFor(s => s.SchoolYear)
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <input type="submit" value="Delete" class="btn btn-primary" />
            @Html.ActionLink("Cancel", "Index", "Semesters")
        </div>
    }
</div>

SchoolJournal/SchoolJournalApp/Views/Semesters/Details.cshtml
@model SchoolJournalModels.Semesters

<div>
    <h2>DETAILS</h2>
    <br />
    <p>@Html.DisplayNameFor(s => s.SemesterID): @Model.SemesterID</p>
    <br />
    <h3>@Html.DisplayNameFor(s => s.SemesterNumber): @Model.SemesterNumber</h3>

    <p>@Html.DisplayNameFor(s => s.SchoolYear): @Model.SchoolYear</p>
    <br />
    <p>@Html.ActionLink("Back to list", "Index", "Semesters")</p>
</div>

SchoolJournal/SchoolJournalApp/Views/Semesters/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<SchoolJournalModels.Semesters>

<br />
<h2>SEMESTERS (@Model.Count records)</h2>
<br />
<div>
    <p>
        <strong>@Html.ActionLink("ADD NEW SEMESTER", "Add", "Semesters")</strong>
    </p>
</div>
<br />
<div>
    @using (Html.BeginForm("Index", "Semesters", FormMethod.Get))
    {
        <b>Search option: </b>
        @Html.RadioButton("option", "Number")<text> Semester Number </text>
        @Html.RadioButton("option", "Year")<text> Year </text>
        @Html.TextBox("search") <input type="submit" value="Search" class="btn btn-primary" />
    }
</div>
<br />
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>Semester Number</th>
                <th>School Year</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count == 0)
            {
                <tr>
                    <td colspan="5">
                        <i>Records not found</i>
                    </td>
                </tr>
            }
            else
            {
                foreach (var semester in Model)
                {
                    <tr>
                        <td>@semester.SemesterNumber</td>
                        <td>@semester.SchoolYear</td>
                        <td>@Html.ActionLink("Details", "Details", "Semesters", new { @id = semester.SemesterID }, null)</td>
                        <td>@Html.ActionLink("Edit", "Update", "Semesters", new { @id = semester.SemesterID }, null)</td>
                        <td>@Html.ActionLink("Delete", "Delete", "Semesters", new { @id = semester.SemesterID }, null)</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<div>
    @Html.PagedListPager(Model, pageNumber => Url.Action("Index", new { pageNumber, option = Request.QueryString["option"], search = Request.QueryString["search"] }))
</div>

SchoolJournal/SchoolJournalApp/Views/Semesters/Update.cshtml
@model SchoolJournalModels.Semesters

<div>
    <h2>UPDATE</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(s => s.SemesterID)
        <div class="form-group">
            @Html.LabelFor(s => s.SemesterNumber)
            @Html.TextBoxFor(s => s.SemesterNumber, null, new { @class = "form-control" })
            @Html.ValidationMessageFor(s => s.SemesterNumber)
        </div>
        <div class="form-group">
            @Html.LabelFor(s => s.SchoolYear)
            @Html.TextBoxFor(s => s.SchoolYear, null, new { @class = "form-control" })
            @Html.ValidationMessageFor(s => s.SchoolYear)
        </div>

        <input type="submit" value="Save" class="btn btn-primary" />
        @Html.ActionLink("Cancel", "Index", "Semesters");
    }
</div>

SchoolJournal/SchoolJournalApp/Views/Subject/Add.cshtml
@model SchoolJournalModels.Subject

<h2><strong>ADD SUBJECT</strong></h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Subject details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(s => s.SubjectName, new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(s => s.SubjectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(s => s.SubjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(s => s.LevelYear, new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(s => s.LevelYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(s => s.LevelYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(s => s.Teachers.TeacherName, new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.DropDownListFor(s => s.TeacherID, new SelectList(Model.TeachersList, "Value", "Text"))
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-9">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to list", "Index", "Subject")
</div>

SchoolJournal/SchoolJournalApp/Views/Subject/Delete.cshtml
@model SchoolJournalModels.Subject


<h2>DELETE</h2>
<h3>Are you sure you want to delete this information?</h3>

<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(s => s.SubjectID)
        </dt>
        <dd>
            @Html.DisplayFor(s => s.SubjectID)
        </dd>

        <dt>
            @Html.DisplayNameFor(s => s.SubjectName)
        </dt>
        <dd>
            @Html.DisplayFor(s => s.SubjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(s => s.LevelYear)
        </dt>
        <dd>
            @Html.DisplayFor(s => s.LevelYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(s => s.Teachers.TeacherID)
        </dt>
        <dd>
            @Html.DisplayFor(s => s.Teachers.TeacherName)
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <input type="submit" value="Delete" class="btn btn-primary" />
            @Html.ActionLink("Cancel", "Index", "Subject")
        </div>
    }
</div>

SchoolJournal/SchoolJournalApp/Views/Subject/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<SchoolJournalModels.Subject>

<h2>COURSES (@Model.Count() records)</h2>

<div>
    <p><strong>@Html.ActionLink("ADD NEW COURSE", "Add", "Subject")</strong></p>
</div>
<br />
<div>
    @using (Html.BeginForm("Index", "Subject", FormMethod.Get))
    {
        <b>Search option: </b>
        @Html.RadioButton("option", "Subject")<text> Course </text>
        @Html.RadioButton("option", "Level")<text> Level year </text>
        @Html.RadioButton("option", "Teacher")<text> Teacher </text>
        @Html.TextBox("search") <input type="submit" value="Search" class="btn btn-primary" />
    }
</div>
<div class="table-responsive">
    <table class="table table-hover table-responsive-sm">
        <thead class="thead-dark">
            <tr>
                <th><b>Course</b></th>
                <th><b>Level year</b></th>
                <th><b>Teacher</b></th>
                <th>@*<input class="form-control" id="myInput" type="text" placeholder="Search..">*@</th>
            </tr>
        </thead>
        <tbody id="myTable">
            @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="4">
                        <i>Records not found</i>
                    </td>
                </tr>
            }
            else
            {
                foreach (var subj in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(m => subj.SubjectName)
                        </td>
                        <td>
                            @Html.DisplayFor(m => subj.LevelYear)
                        </td>
                        <td>
                            @Html.ActionLink(@Html.DisplayFor(m => subj.Teachers.TeacherName).ToString(), "Details", "Teacher", new { id = subj.TeacherID }, null)
                        </td>
                        <td>
                            @Html.ActionLink("Details", "Details", "Subject", new { id = subj.SubjectID }, null) |
                            @Html.ActionLink("Edit", "Update", "Subject", new { id = subj.SubjectID }, null) |
                            @Html.ActionLink("Delete", "Delete", "Subject", new { id = subj.SubjectID }, null)
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<div>
    @Html.PagedListPager(Model, pageNumber => Url.Action("Index", new { pageNumber, option = Request.QueryString["option"], search = Request.QueryString["search"] }))
    Showing @Model.FirstItemOnPage to @Model.LastItemOnPage of @Model.TotalItemCount courses
</div>
@*<script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>*@

SchoolJournal/SchoolJournalApp/Views/Subject/Update.cshtml
@model SchoolJournalModels.Subject

<div>
    <h2>UPDATE</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(s => s.SubjectID)
        <div class="form-group">
            @Html.LabelFor(s => s.SubjectName)
            @Html.TextBoxFor(s => s.SubjectName, null, new { @class = "form-control" })
            @Html.ValidationMessageFor(s => s.SubjectName)
        </div>
        <div class="form-group">
            @Html.LabelFor(s => s.LevelYear)
            @Html.TextBoxFor(s => s.LevelYear, null, new { @class = "form-control" })
            @Html.ValidationMessageFor(s => s.LevelYear)
        </div>
        <div class="form-group">
            @Html.LabelFor(s => s.Teachers.TeacherName)
            @Html.DropDownListFor(s => s.TeacherID, new SelectList(Model.TeachersList, "Value", "Text"))
        </div>

        <input type="submit" value="Save" class="btn btn-primary" />
        @Html.ActionLink("Cancel", "Index", "Subject");
    }
</div>